name: ocms_16s
channels:
  - r
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - bioconductor-dada2=1.14.0
  - cgat-apps=0.6.0
  - cgatcore=0.6.5
  - r-base=3.6.1
  - r-dplyr=1.0.2
  - r-ggplot2=3.3.2
  - r-gplots=3.1.0
  - r-gridextra=2.3
  - r-gtools=3.8.2
  - r-markdown=1.1
  - r-optparse=1.6.6
  - r-plotly=4.9.2.1
  - r-rcolorbrewer=1.1_2
  - r-rcppparallel=5.0.2
  - r-reshape=0.8.8
  - r-rmarkdown=2.5
  - python=3.7.1