name: ocms_16s
channels:
  - bioconda
  - conda-forge
  - r
  - defaults
dependencies:
  - _r-mutex=1.0.0
  - aiosignal=1.3.1
  - argcomplete=2.0.0
  - async-timeout=4.0.2
  - attrs=22.1.0
  - bioconductor-biobase=2.58.0
  - bioconductor-biocgenerics=0.44.0
  - bioconductor-biocparallel=1.32.0
  - bioconductor-biostrings=2.66.0
  - bioconductor-dada2=1.26.0
  - bioconductor-data-packages=20221112
  - bioconductor-delayedarray=0.24.0
  - bioconductor-genomeinfodb=1.34.1
  - bioconductor-genomeinfodbdata=1.2.9
  - bioconductor-genomicalignments=1.34.0
  - bioconductor-genomicranges=1.50.0
  - bioconductor-iranges=2.32.0
  - bioconductor-matrixgenerics=1.10.0
  - bioconductor-rhtslib=2.0.0
  - bioconductor-rsamtools=2.14.0
  - bioconductor-s4vectors=0.36.0
  - bioconductor-shortread=1.56.0
  - bioconductor-summarizedexperiment=1.28.0
  - bioconductor-xvector=0.38.0
  - bioconductor-zlibbioc=1.44.0
  - boto3=1.26.8
  - botocore=1.29.8
  - bwidget=1.9.14
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.10.11
  - cachetools=4.2.4
  - cairo=1.16.0
  - cctools_osx-64=973.0.1
  - cgatcore=0.6.14
  - charset-normalizer=2.1.1
  - clang=14.0.6
  - clang-14=14.0.6
  - clang_osx-64=14.0.6
  - clangxx=14.0.6
  - clangxx_osx-64=14.0.6
  - compiler-rt=14.0.6
  - compiler-rt_osx-64=14.0.6
  - coreutils=8.25
  - curl=7.86.0
  - drmaa=0.7.9
  - expat=2.5.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.1
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.12.1
  - fribidi=1.0.10
  - ftputil=5.0.4
  - gettext=0.21.1
  - gfortran_impl_osx-64=11.3.0
  - gfortran_osx-64=11.3.0
  - gmp=6.2.1
  - google-api-core=1.31.5
  - google-auth=1.35.0
  - google-cloud-core=1.6.0
  - google-cloud-sdk=409.0.0
  - google-cloud-storage=2.2.0
  - google-resumable-media=2.4.0
  - graphite2=1.3.13
  - gsl=2.7
  - harfbuzz=5.3.0
  - icu=70.1
  - idna=3.4
  - importlib_metadata=4.11.4
  - isl=0.25
  - jmespath=1.0.1
  - jpeg=9e
  - jq=1.5
  - krb5=1.19.3
  - ld64_osx-64=609
  - lerc=4.0.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libclang-cpp14=14.0.6
  - libcrc32c=1.1.2
  - libcurl=7.86.0
  - libcxx=14.0.6
  - libdeflate=1.14
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.2
  - libgcc=4.8.5
  - libgfortran=5.0.0
  - libgfortran-devel_osx-64=11.3.0
  - libgfortran5=11.3.0
  - libglib=2.74.1
  - libiconv=1.17
  - liblapack=3.9.0
  - libllvm11=11.1.0
  - libllvm14=14.0.6
  - libnghttp2=1.47.0
  - libopenblas=0.3.21
  - libpng=1.6.38
  - libprotobuf=3.21.9
  - libsodium=1.0.18
  - libsqlite=3.39.4
  - libssh2=1.10.0
  - libtiff=4.4.0
  - libuv=1.44.2
  - libwebp-base=1.2.4
  - libxml2=2.10.3
  - libzlib=1.2.13
  - llvm-openmp=15.0.4
  - llvm-tools=14.0.6
  - make=4.3
  - mpc=1.2.1
  - mpfr=4.1.0
  - ncurses=6.3
  - nomkl=1.0
  - openssl=3.0.7
  - packaging=21.3
  - pandoc=2.12
  - pango=1.50.11
  - paramiko=2.12.0
  - pcre2=10.40
  - pip=22.3.1
  - pixman=0.40.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.21
  - pyopenssl=22.1.0
  - pyparsing=3.0.9
  - pysftp=0.2.9
  - python=3.10.6
  - python-dateutil=2.8.2
  - python_abi=3.10
  - pytz=2022.6
  - pyu2f=0.1.5
  - r-askpass=1.1
  - r-base=4.2.2
  - r-base64enc=0.1_3
  - r-bh=1.78.0_0
  - r-bitops=1.0_7
  - r-brio=1.1.3
  - r-bslib=0.3.1
  - r-callr=3.7.0
  - r-catools=1.18.2
  - r-cli=3.4.1
  - r-codetools=0.2_18
  - r-colorspace=2.0_3
  - r-commonmark=1.8.1
  - r-cpp11=0.4.2
  - r-crayon=1.5.1
  - r-crosstalk=1.2.0
  - r-curl=4.3.3
  - r-data.table=1.14.4
  - r-desc=1.4.1
  - r-diffobj=0.3.5
  - r-digest=0.6.30
  - r-dplyr=1.0.10
  - r-ellipsis=0.3.2
  - r-evaluate=0.15
  - r-fansi=1.0.3
  - r-farver=2.1.1
  - r-fastmap=1.1.0
  - r-formatr=1.12
  - r-fs=1.5.2
  - r-futile.logger=1.4.3
  - r-futile.options=1.0.1
  - r-generics=0.1.2
  - r-getopt=1.20.3
  - r-ggplot2=3.3.6
  - r-glue=1.6.2
  - r-gplots=3.1.3
  - r-gridextra=2.3
  - r-gtable=0.3.0
  - r-gtools=3.9.3
  - r-highr=0.9
  - r-htmltools=0.5.3
  - r-htmlwidgets=1.5.4
  - r-httr=1.4.3
  - r-hwriter=1.3.2.1
  - r-isoband=0.2.6
  - r-jpeg=0.1_9
  - r-jquerylib=0.1.4
  - r-jsonlite=1.8.3
  - r-kernsmooth=2.23_20
  - r-knitr=1.39
  - r-labeling=0.4.2
  - r-lambda.r=1.2.4
  - r-later=1.2.0
  - r-lattice=0.20_45
  - r-latticeextra=0.6_29
  - r-lazyeval=0.2.2
  - r-lifecycle=1.0.1
  - r-magrittr=2.0.3
  - r-markdown=1.3
  - r-mass=7.3_58.1
  - r-matrix=1.5_3
  - r-matrixstats=0.62.0
  - r-mgcv=1.8_41
  - r-mime=0.12
  - r-munsell=0.5.0
  - r-nlme=3.1_160
  - r-openssl=2.0.4
  - r-optparse=1.7.1
  - r-pillar=1.7.0
  - r-pkgconfig=2.0.3
  - r-pkgload=1.2.4
  - r-plotly=4.10.0
  - r-plyr=1.8.8
  - r-png=0.1_7
  - r-praise=1.0.0
  - r-processx=3.8.0
  - r-promises=1.2.0.1
  - r-ps=1.7.2
  - r-purrr=0.3.5
  - r-r6=2.5.1
  - r-rappdirs=0.3.3
  - r-rcolorbrewer=1.1_3
  - r-rcpp=1.0.9
  - r-rcppparallel=5.1.5
  - r-rcurl=1.98_1.9
  - r-rematch2=2.1.2
  - r-reshape=0.8.9
  - r-reshape2=1.4.1
  - r-rlang=1.0.6
  - r-rmarkdown=2.14
  - r-rprojroot=2.0.3
  - r-rstudioapi=0.13
  - r-sass=0.4.2
  - r-scales=1.2.0
  - r-snow=0.4_4
  - r-stringi=1.7.8
  - r-stringr=1.4.0
  - r-sys=3.4.1
  - r-testthat=3.1.5
  - r-tibble=3.1.8
  - r-tidyr=1.2.1
  - r-tidyselect=1.1.2
  - r-tinytex=0.39
  - r-utf8=1.2.2
  - r-vctrs=0.4.2
  - r-viridislite=0.4.0
  - r-waldo=0.4.0
  - r-withr=2.5.0
  - r-xfun=0.34
  - r-yaml=2.3.6
  - readline=8.1.2
  - requests=2.28.1
  - rsa=4.9
  - ruffus=2.8.4
  - s3transfer=0.6.0
  - setuptools=65.5.1
  - sigtool=0.1.3
  - six=1.16.0
  - sqlite=3.39.4
  - tapi=1100.0.11
  - time=1.8
  - tk=8.6.12
  - tktable=2.10
  - toml=0.10.2
  - typing-extensions=4.4.0
  - typing_extensions=4.4.0
  - tzdata=2022f
  - urllib3=1.26.11
  - wheel=0.38.4
  - xmltodict=0.13.0
  - xz=5.2.6
  - yaml=0.2.5
  - yq=2.13.0
  - zipp=3.10.0
  - zlib=1.2.13
  - zope.event=4.5.0
  - zope.interface=5.5.1
  - zstd=1.5.2
  - pip:
    - aiohttp==3.8.3
    - apsw==3.39.4.0
    - bcrypt==3.2.2
    - brotlipy==0.7.0
    - certifi==2022.9.24
    - cffi==1.15.1
    - cryptography==38.0.3
    - frozenlist==1.3.3
    - gevent==22.10.2
    - google-crc32c==1.1.2
    - googleapis-common-protos==1.56.4
    - greenlet==2.0.1
    - importlib-metadata==4.11.4
    - multidict==6.0.2
    - numpy==1.23.4
    - ocms-16s==0.0.2
    - pandas==1.5.1
    - protobuf==4.21.9
    - pynacl==1.5.0
    - pysocks==1.7.1
    - pyyaml==6.0
    - sqlalchemy==1.4.44
    - yarl==1.8.1
    - zope-interface==5.5.1

