
# specify whether data are paired or single end. The
# pipeline will pick up whether this is true but being
# explicit here is helpful
paired: 1

scriptsdir: /gfs/devel/nilott/NGSKit/R

trim:

    # parameters used for trimming reads. If the data are
    # paired-end then you need to specify 2 values for
    # maxee, truncLen and trimLeft. These parameters must be specified
    maxn: 0
    maxee: 2,2
    truncq: 2
    trunclen: 250,160
    trimleft: 0,0

sample_inference:

    # paramters for sample inference. This includes
    # error learning, de-replication, merging (if paired) and
    # sample inference.

    # number of reads to use (per sample) to estimate error
    # model
    nbases: 10000000
    options: ''

taxonomy:

    memory: 10G

    # assigning taxonomy
    taxonomy_file: /gfs/mirror/dada2/RefSeq-RDP16S_v2_May2018.fa.gz
    species_file: /gfs/mirror/dada2/silva_species_assignment_v132.fa.gz

report:
    # whether to run diagnostics report. specify as 1 if you wish to run it
    diagnostics:
    directory: /gfs/devel/nilott/NGSKit/pipelines/docs/Rmd/pipeline_dada2
    author: Nick Ilott
    title: Calprotectin project